trversal/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from api import views
from django.views.generic import TemplateView

router = routers.DefaultRouter()
router.register(r'trips', views.TripViewSet)
router.register(r'locs', views.LocViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('trversal/user/', include('users.urls')),
    path('', include('trversalapp.urls')),
    path('api/recalc/trips/<int:pk>/', views.ReCalcTrip.as_view()),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('test', TemplateView.as_view(template_name="api_test_js.html")),
    path('test2/<int:pk>/', views.LocDetail.as_view()),

]

trversalapp/urls.py
from django.urls import path
from . import views

app_name = 'trversal' 
urlpatterns = [
    path('', views.home, name='home'),

    path('index', views.IndexListView.as_view(), name='index'),
    path('new_trip/', views.TripCreateView.as_view(), name='new-trip'),
    path('<int:pk>/trip/', views.TripDetailView.as_view(), name='view-trip'),
    path('<int:pk>/trip/del', views.TripDeleteView.as_view(), name='del-trip'),
    path('<int:pk>/trip/edit', views.TripUpdateView.as_view(), name='edit-trip'),

    # path('api/trip/<int:pk>', views.tripAPIdetail, name='trip-api'),

    # path('<int:pk>/new_day/', views.DayCreateView.as_view(), name='new-day'),
    # path('<int:pk>/day/', views.DayDetailView.as_view(), name='view-day'),
    # path('<int:pk>/day/del', views.DayDeleteView.as_view(), name='del-day'),
    # path('<int:pk>/day/edit', views.DayUpdateView.as_view(), name='edit-day'),

    path('<int:pk>/new_loc/', views.LocCreateView.as_view(), name='new-loc'),
    path('<int:pk>/loc/', views.LocDetailView.as_view(), name='view-loc'),
    path('<int:pk>/loc/del', views.LocDeleteView.as_view(), name='del-loc'),
    path('<int:pk>/loc/edit', views.LocUpdateView.as_view(), name='edit-loc'),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('', views.home, name='home'),
    path('userlist', views.UserListView.as_view(), name='user_list'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('<str:username>/edit/', views.SignUpView.as_view(), name='edit-user'),
    path('<str:username>/', views.MyTripList.as_view(), name='mytrip_list'),
]

trversalapp/models.py
from django.db import models
from django.urls import reverse, reverse_lazy

from datetime import datetime as dt



from . import choices

class Trip(models.Model):
    name = models.CharField(max_length=100)
    start_time = models.TimeField(max_length=20,default="9:00 AM")
    creator = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    date = models.DateField(null=True, blank=True)
    mode = models.CharField(max_length=20,choices=choices.travel_choices,default="DRIVING")

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('trversal:edit-trip', args=[str(self.id)])

    @property
    def past_trip(self):
        # return self.start_day > dt.today()
        return dt.strptime(str(self.date), "%Y-%m-%d") < dt.today()


class Location(models.Model):
    g_name = models.TextField(max_length=250,default=" ")
    g_lat = models.FloatField(null=True, blank=True)
    g_lng= models.FloatField(null=True, blank=True)
    name = models.TextField(default=" ")
    duration_hour = models.CharField(max_length=20,choices=choices.hour_choices,default="1")
    duration_min = models.CharField(max_length=20,choices=choices.min_choices,default="15")
    route_time = models.TextField(null=True, blank=True)
    time_arr = models.TextField(null=True, blank=True)
    time_leave = models.TextField(null=True, blank=True)
    order = models.IntegerField(default=1)
    trip = models.ForeignKey("Trip", related_name="locs", on_delete=models.CASCADE)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('trversal:view-loc', args=[str(self.id)])

    

    
    # def delete(self, request, *args, **kwargs):
    #     self.day_pk = self.get_object().day.pk
    #     return super(LocDeleteView, self).delete(request, *args, **kwargs)

templates/api_test_js.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
      <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDs27HLOoV6keN4f7cGfspYlJc5HSdEl78&libraries=places"></script>
    </head>
    <body>
        <input type="text" id="autocomplete"/>
        <div id="test">
        {% csrf_token %}
        </div>


<script>

    function init() {
          var input = document.getElementById('autocomplete');
          var autocomplete = new google.maps.places.Autocomplete(input);
      }

      google.maps.event.addDomListener(window, 'load', init);

    const div = document.getElementById('test');
    const url = 'http://localhost:8000/api/trips/1/?format=json';
    fetch(url)
    .then((response) => response.json())
    .then(function(data) {
        console.log(data)
        let i=0
        let p = document.createElement("p")
        p.innerText = data.name
        div.append(p)
        data.days.forEach(function(){
            let p = document.createElement("p")
            p.innerText = data.days[i].day_date
            div.append(p)
            let ul=  document.createElement("ul")
            div.append(ul)
            let j = 0
            data.days[i].locs.forEach(function(){
                let li = document.createElement("li")
                li.innerText = data.days[i].locs[j].name
                div.append(li)
                j++
            })
            i++
        })
        {% comment %} data.forEach(function(){
            
            console.log(data.name)
            let p = document.createElement("p");
            p.innerText = `${data[i].name}`;
            let btn = document.createElement("button");
            btn.innerText = "Down"
            btn.id = data[i].order; 
            btn.addEventListener("click", moveUp(){
                id = this.id
                idDown = id++
                if (document.getElementById(:idDown)):

            })    
            div.append(p);  
            div.append(btn);  
            i++
        }) {% endcomment %}
    })
     .catch(function(error) {
    console.log(error);
  });   
 
  {% comment %} fetch('http://localhost:8000/test2/`${pk}`', {
  headers: { "Content-Type": "application/json; charset=utf-8" },
  method: 'PUT',
  body: JSON.stringify({
    g_name = document.getElementById('autocomplete')
  })
}) {% endcomment %}
</script> 

templates/base.html
 {% load static %}

  <!DOCTYPE html>
<html>
    <head>
      <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
       <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
      <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'style.css' %}">

      {% block head %}
      {% endblock %}
    </head>
    <body>
      <div class="container">
        <div class="header">
          {% if user.is_authenticated %}
            <div class="user">Welcome back, {{ user.username }}!</a><br>
            <a href="{% url 'users:mytrip_list' user %}">My Trips</a>
            
            </div>
            <div class="login"><a href="{% url 'logout' %}">Logout</a><br>
            {% now "l M d h:i A" %}
            </div>
          {% else %}
            <div class="user">Welcome!</a></div>
            <div class="login"><a href="{% url 'login' %}">Login</a><br>
            {% now "l M d h:i A" %}
            </div>
          {% endif %}
          <div class="logo">
            <a class="home" href="{% url 'trversal:home' %}">
            <p class="title">TRVERSAL</p>
            <img class="logo-img" src="{% static 'logo-192x192-w.png' %}">
            </a>
          </div>
        </div>
        <div class="content">
          {% block body %}
          {% endblock %}
        </div>
      </div>
    </body>
      {% block js %}
      {% endblock %}
  </html>

templates/del_loc.html
{% extends 'base.html' %}
{% block head %}
  <title> Delete {{ location }}?</title>
{% endblock %}

{% block body %}
<h1>Delete Location</h1>
  <form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ location.name }} on {{ location.day }} of your {{ location.day.trip_name.name }} Trip"?</p>
    <input type="submit" value="Confirm">
  </form>
{% endblock %}

templates/edit_day.html
{% extends 'base.html' %}

{% block head %}
  <title> Edit {{ Day }}</title>
{% endblock %}

{% block body %}

{% if user == day.trip_name.creator %}

<h1 class="page-title">{{ day }} of your {{day.trip_name.name}} Trip</h1>
  <div class="edit-day">
    <div class="edit-day-form">
      <h3> Edit {{ day }}:</h3>
      <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
      </form>
      <a href="{% url 'trversal:view-day' day.pk %}"><button class="btn">Back to Day</button></a>
      <a href="{% url 'trversal:del-day' day.pk %}"><button class="btn">Delete Day</button></a>
    </div>
    <div class="edit-day-info">
      <h2>Current info:</h2>
      <h3>{{ day.day_date|date:"l, F d " }}</h3>
      <h3>Current Start Time:</h3>
      <h4> {{ day.start_time }}</h4>
      <h3> Calculate Directions in</h3>
      <h4> {{day.mode|lower|capfirst }} Mode </h4>
    </div>
  </div>
  {% else %}
  <h1 class="page-title">This is not your Trip<br>Please login. </h1>
  {% endif %}
{% endblock %}

templates/edit_trip.html
{% extends 'base.html' %}

{% block head %}
  <title>Edit {{ trip.name }}</title>
{% endblock %}

{% block body %}

{% if user == trip.creator %}

<h1 class="page-title">Your "{{ trip }}" Trip:</h1>
<div class="edit-trip">
  <div class="edit-trip-form">
    <h4> Edit your trip: </h4>
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Update">
    </form>
    <a href="{% url 'trversal:view-trip' trip.pk %}"><button class="btn">Back to Trip</button></a>
    <a href="{% url 'trversal:del-trip' trip.pk %}"><button class="btn">Delete Trip</button></a>
  </div>
  {% comment %} <div class="edit-trip-days">
    <h2> Day-by-Day for "{{ trip }}":</h2>
    <ul>
    {% for day in trip.days.all %}
      <li>
        <a href="{% url 'trversal:view-trip' day.pk %}">
        <h3 class="day-2-day">{{ day }}:</h3>
        <button class="btn-icon2"><i class="fas fa-map-marked-alt fa-lg"></i>Build Day</button></a>
        <a href="{% url 'trversal:edit-day' day.pk %}"><button class="btn-icon2"><i class="fas fa-pencil-alt fa-lg"></i>Day Settings</button></a>
        <a href="{% url 'trversal:del-day' day.pk %}"><button class="btn-icon2"><i class="fas fa-trash fa-lg"></i>Delete</button></a><br>
        <h4>{{ day.day_date|date:"l, F d " }} -- {{day.mode|lower|capfirst }} Directions -- {{ day.locs.count }} Stop{{ day.locs.count|pluralize}}</h4>
      </li>
    {% endfor %}
    </ul>
    <a href="{% url 'trversal:new-day' trip.pk %}"><button class="btn">+Add Day</button></a>
  </div> 
</div>
{% endcomment %}

{% else %}
<h1 class="page-title">This is not your Trip<br>Please login. </h1>
{% endif %}

{% endblock %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
      <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDs27HLOoV6keN4f7cGfspYlJc5HSdEl78&libraries=places"></script>
    </head>
    <body>
      <img src="{%  static 'logo-192x192.png' %}" height="40">Trversal
      <ul>
      {% for trip in trip_list %}
        <li><a href="{% url 'trversal:view-trip' trip.id %}"><h1>{{ trip }} </h1></a></li>
        <ul>
          {% for day in trip.days.all %}
            <li><a href="{% url 'trversal:view-day' day.pk %}"><h2>{{ day.day_date|date:"l -- F d " }} -- {{ day.start_time|date:"g:i A " }}</h2></a></li>
            <ul>
              {% for l in day.locs.all %}
                <li><h3>{{ l.name }}</h3>
                {{ l.time_arr }} - {{ l.time_leave }}</li>
              {% endfor %}
            </ul>
          {% endfor %}
        </ul>
      {% endfor %}
    </ul>
    <p><a href="{% url 'trversal:new-trip' %}">Plan New Trip</a></p>
    <p><a href="{% url 'trversal:index' %}">All Trips</a></p>
    <script>
      function init() {
          var input = document.getElementById('autocomplete');
          var autocomplete = new google.maps.places.Autocomplete(input);
      }

      google.maps.event.addDomListener(window, 'load', init);

    </script>
  </body>
</html>

templates/my_trips.html
{% extends 'base.html' %}

{% block head %}
  <title>{{ user_page }}'s Trips</title>
{% endblock %}

{% block body %}

    <div class="my-page">
        <div class="user-title"><h4>{{ user_page }}'s Travels:</h4></div>
        <div class="user-info">
            <p class="new-trip-icon"><a href="{% url 'trversal:new-trip' %}"><i class="fas fa-map fa-10x"></i><br><i class="fas fa-plus"></i> Plan New Trip</a></p>
            <p> Date joined: {{ user_page.date_joined }}</p>
            <p> {{ user_page.first_name }} {{ user_page.last_name }}

            {% if user == user_page %}
            {% comment %} <a href="{% url 'password_change' %}" ><i class="fas fa-key"></i> Change Password</a><br> {% endcomment %}
            <a href="{% url 'users:edit-user' user %}"><i class="fas fa-user-edit"></i> Edit My Info</a>
            {% endif %}

        </div>
        <div class="flex-trips">

            {% for trip in trip_list %}

                {% if trip.past_trip == False %}
                <div class="mytrips">
                <a href="{% url 'trversal:view-trip' trip.pk %}" ><i class="fas fa-map-marked-alt fa-10x"></i><br></a>
                <h3>{{ trip }}</h3>
                <p>{{ trip.date}}</p>
                {% comment %} <p>{{ trip.days_num}} Day{{ trip.days_num|pluralize }}</p> {% endcomment %}
                </div>
                {% endif %}

            {% endfor %}
        </div>
        <div class="past"><h3>Past Trips:</h3></div>
        <div class="flex-trips-past">
            
            {% for trip in trip_list %}

                {% if trip.past_trip %}
                <div class="mytrips-past">
                    <a href="{% url 'trversal:view-trip' trip.pk %}" ><i class="fas fa-map-marked-alt fa-10x"></i><br></a>
                    <h3>{{ trip }}</h3>
                    <p>{{ trip.date}}</p>
                    {% comment %} <p>{{ trip.days_num}} Day{{ trip.days_num|pluralize }}</p> {% endcomment %}
                </div>
                {% endif %}

            {% endfor %}
        </div>
    </div>

{% endblock %}
{% block js %}
<script>
    const listItems = document.getElementsByClassName("flex-trips")[0].getElementsByClassName('fas fa-map-marked-alt fa-10x');
    const colors = ["#2790D6", "#28C7E0", "#2EC9B5", "#28E094", "#27D65B", ];
    for(var i = 0; i < listItems.length; i ++) {
        listItems[i].style.color = colors[i%5]; 
    }
    const listItemsPast = document.getElementsByClassName("flex-trips-past")[0].getElementsByClassName('fas fa-map-marked-alt fa-10x');
    const colorsPast = ["#7AA4BF", "#81BFC9", "#7BB3AB", "#81C9AB", "#7ABF8F", ];
    for(var i = 0; i < listItemsPast.length; i ++) {
        listItemsPast[i].style.color = colorsPast[i%5]; 
    }
</script>
{% endblock %}

templates/new_day.html
{% extends 'base.html' %}
{% block head %}
  <title>Add Day</title>
{% endblock %}

{% block body %}
<div class=" new-day">

    <h1> Start planning a new day:</h1>
    <form class="new-day" action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      {{form.duration_hour.label|linebreaksbr}}
      <button class="btn" type="submit" value="Add">Add</button>
    </form>
  </div>
{% endblock %}

templates/new_loc.html
{% extends 'base.html' %}

{% block head %}
  <title>New Locations</title>

  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDs27HLOoV6keN4f7cGfspYlJc5HSdEl78&libraries=places"></script>
{% endblock %}
{% block body %}    
  <form class="new-loc" action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="new-loc-btn" type="submit" value="Add">Add</button>
  </form>
{% endblock %}
{% block js %}
  <script>
    function init() {
        var input = document.getElementById('autocomplete');
        var autocomplete = new google.maps.places.Autocomplete(input);
    }

    google.maps.event.addDomListener(window, 'load', init);

  </script>
{% endblock %}

templates/new_trip.html
{% extends 'base.html' %}

{% block head %}
  <title>Plan A New Trip</title>
{% endblock %}

{% block body %}
  <form class="new-trip" action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="new-trip-btn" type="submit" value="Add">Add</button>
  </form>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block body %}
  <h2>Sign Up</h2>
  <div class="signup">
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Sign Up">
  </form>
  </div>
{% endblock %}

templates/view_day.html
<div class="day-detail">
    <h1 class="day-name">{{ day.trip_name.name }}<br></h1>
    <h2 class="day-name">{{ day }}</h2>
    <h2 class="day-date">{{ day.day_date|date:"D , F d " }}</h2>
    <h2 class="day-start">{{ day.start_time|date:"g:i A " }}</h2>
    <ul>
        {% for l in day.locs.all %}
        <li><a href="{% url 'trversal:view-loc' l.id %}">{{ l.name }}</a> 
        {% comment %} -- Staying for 
        {% if l.duration_hour %}{{ l.duration_hour }}hour {% endif %}
        {% if l.duration_min %}{{ l.duration_min }}min{% endif %}<br>{% endcomment %}
        <br>
        Arrive at -- {{ l.time_arr }}<br> 
        Leave by -- {{ l.time_leave }}
        </li>

        {% endfor %}
    </ul>
    <h4 class="day-time"><em>Planned by {{ day.trip_name.creator }}</em></h4>
    <p><a href="{% url 'trversal:new-loc' day.pk  %}">Add Location</a></p>
    <p><a href="{% url 'trversal:view-trip' day.trip_name.pk  %}">Back to Trip</a></p>
    <p><a href="{% url 'trversal:index' %}">All Trips</a></p>

</div>

templates/view_loc.html
{% extends 'base.html' %}

{% block body %}
<div class="location-detail">
    <h1 class="location-name">{{ location.trip.name }}<br></h1>
    <h2 class="location-text"><a href="">{{ location.trip }}</a></h2>
    <h2 class="location-text"><a href="">{{ location.trip.start_time }}</a></h2>
    <h2 class="location-text"><a href="">{{ location.name }}</a></h2>
    <h3 class="location-text"><a href="">{{ location.time_arr }} -- {{ location.time_leave }}</a></h3>
    <h4 class="location-time"><em>Planned by {{ location.trip.creator }}</em></h4>
    <p><a href="{% url 'trversal:new-loc' location.day.pk  %}">Add Location</a></p>
    {% comment %} <p><a href="{% url 'trversal:view-day' location.day.pk  %}">Back to Day</a></p> {% endcomment %}
    <p><a href="{% url 'trversal:view-trip' location.trip.pk  %}">Back to Trip</a></p>

    <p><a href="{% url 'trversal:index' %}">All Trips</a></p>

</div>
{% endblock %}